---
html:
  toc: true
title: About
jupyter: python3
---

Cristiano Ronaldo dos Santos Aveiro GOIH ComM; born 5 February 1985 is a Portuguese professional footballer who plays as a forward for and captains both Saudi Pro League club Al Nassr and the Portugal national team. Widely regarded as one of the greatest players of all time, Ronaldo has won five Ballon d'Or awards,[note 3] a record three UEFA Best Player in Europe, and four European Golden Shoes, the most by a European player. He has won 33 trophies in his career, including seven league titles, five UEFA Champions Leagues, the UEFA European Championship and the UEFA Nations League. Ronaldo holds the records for most appearances (183), goals (140) and assists (42) in the Champions League, goals in the European Championship (14), international goals (123) and international appearances (200). He is one of the few players to have made over 1,100 professional career appearances, and has scored over 800 official senior career goals for club and country, making him the highest goalscorer of all time.

## Rivarly with Lionel Messi
Ronaldo is widely regarded as one of the two best players of his generation, alongside Lionel Messi. Winning his first Ballon d'Or in 2008 by a record-high vote count at age 23, over the next decade Ronaldo has often featured in debates concerning who is the greatest player in history. Acclaimed for his prolific and consistent goal-scoring, he is considered a decisive player who is also a game changer, especially in important and high-pressured situations

### Underlying records
- Ronaldo has the most weak foot goals and headed goals in history
- He has the most game tying / winning goals in football history
- He is the only player in history to win the PFA player of the year and young player of the year in the same season


```{python}
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)
y = np.sin(x)
plt.plot(x, y)
plt.show()
```

